CREATE DATABASE IF NOT exists hotel;
USE hotel;

CREATE TABLE Reservas (
id_reserva int auto_increment not null primary key,
fecha_entrada date not null,
fecha_salida date,
valor decimal(10,2),
forma_pago varchar(50)
);

CREATE TABLE Paises (
    id_pais INT PRIMARY KEY AUTO_INCREMENT,
    nombre VARCHAR(100) NOT NULL,
    prefijo_telefono VARCHAR(50) NOT NULL,
    nacionalidad VARCHAR(100) NOT NULL
);

INSERT INTO paises (nombre, prefijo_telefono, nacionalidad) VALUES
    ('Afganistán', '+93', 'Afgano'),
    ('Albania', '+355', 'Albanés'),
    ('Alemania', '+49', 'Alemán'),
    ('Andorra', '+376', 'Andorrano'),
    ('Angola', '+244', 'Angoleño'),
    ('Antigua y Barbuda', '+1-268', 'Antiguano, Barbudano'),
    ('Arabia Saudita', '+966', 'Saudí'),
    ('Argelia', '+213', 'Argelino'),
    ('Argentina', '+54', 'Argentino'),
    ('Armenia', '+374', 'Armenio'),
    ('Australia', '+61', 'Australiano'),
    ('Austria', '+43', 'Austríaco'),
    ('Azerbaiyán', '+994', 'Azerbaiyano'),
    ('Bahamas', '+1-242', 'Bahameño'),
    ('Bangladés', '+880', 'Bangladesí'),
    ('Barbados', '+1-246', 'Barbadense'),
    ('Baréin', '+973', 'Bahreiní'),
    ('Bélgica', '+32', 'Belga'),
    ('Belice', '+501', 'Beliceño'),
    ('Benín', '+229', 'Beninés'),
    ('Bielorrusia', '+375', 'Bielorruso'),
    ('Birmania', '+95', 'Birmano'),
    ('Bolivia', '+591', 'Boliviano'),
    ('Bosnia y Herzegovina', '+387', 'Bosnio, Herzegovino'),
    ('Botsuana', '+267', 'Botsuano'),
    ('Brasil', '+55', 'Brasileño'),
    ('Brunéi', '+673', 'Bruneano'),
    ('Bulgaria', '+359', 'Búlgaro'),
    ('Burkina Faso', '+226', 'Burkinés'),
    ('Burundi', '+257', 'Burundés'),
    ('Bután', '+975', 'Butanés'),
    ('Cabo Verde', '+238', 'Caboverdiano'),
    ('Camboya', '+855', 'Camboyano'),
    ('Camerún', '+237', 'Camerunés'),
    ('Canadá', '+1', 'Canadiense'),
    ('Catar', '+974', 'Catarí'),
    ('Chad', '+235', 'Chadiano'),
    ('Chile', '+56', 'Chileno'),
    ('China', '+86', 'Chino'),
    ('Chipre', '+357', 'Chipriota'),
    ('Colombia', '+57', 'Colombiano'),
    ('Comoras', '+269', 'Comorense'),
    ('Congo (Brazzaville)', '+242', 'Congoleño'),
    ('Congo (Kinshasa)', '+243', 'Congoleño'),
    ('Corea del Norte', '+850', 'Norcoreano'),
    ('Corea del Sur', '+82', 'Surcoreano'),
    ('Costa de Marfil', '+225', 'Marfileño'),
    ('Costa Rica', '+506', 'Costarricense'),
    ('Croacia', '+385', 'Croata'),
    ('Cuba', '+53', 'Cubano'),
    ('Dinamarca', '+45', 'Danés'),
    ('Dominica', '+1-767', 'Dominiqués'),
    ('Ecuador', '+593', 'Ecuatoriano'),
    ('Egipto', '+20', 'Egipcio'),
    ('El Salvador', '+503', 'Salvadoreño'),
    ('Emiratos Árabes Unidos', '+971', 'Emiratí'),
    ('Eritrea', '+291', 'Eritreo'),
    ('Eslovaquia', '+421', 'Eslovaco'),
    ('Eslovenia', '+386', 'Esloveno'),
    ('España', '+34', 'Español'),
    ('Estados Unidos', '+1', 'Estadounidense'),
    ('Estonia', '+372', 'Estonio'),
    ('Etiopía', '+251', 'Etíope'),
    ('Filipinas', '+63', 'Filipino'),
    ('Finlandia', '+358', 'Finlandés'),
    ('Fiyi', '+679', 'Fiyiano'),
    ('Francia', '+33', 'Francés'),
    ('Gabón', '+241', 'Gabonés'),
    ('Gambia', '+220', 'Gambiano'),
    ('Georgia', '+995', 'Georgiano'),
    ('Ghana', '+233', 'Ghanés'),
    ('Granada', '+1-473', 'Granadino'),
    ('Grecia', '+30', 'Griego'),
    ('Guatemala', '+502', 'Guatemalteco'),
    ('Guinea', '+224', 'Guineano'),
    ('Guinea-Bisáu', '+245', 'Bisau-guineano'),
    ('Guinea Ecuatorial', '+240', 'Ecuatoguineano'),
    ('Guyana', '+592', 'Guyanés'),
    ('Haití', '+509', 'Haitiano'),
    ('Honduras', '+504', 'Hondureño'),
    ('Hungría', '+36', 'Húngaro'),
    ('India', '+91', 'Indio'),
    ('Indonesia', '+62', 'Indonesio'),
    ('Irak', '+964', 'Iraquí'),
    ('Irán', '+98', 'Iraní'),
    ('Irlanda', '+353', 'Irlandés'),
    ('Islandia', '+354', 'Islandés'),
    ('Islas Marshall', '+692', 'Marshallés'),
    ('Islas Salomón', '+677', 'Salomonense'),
    ('Israel', '+972', 'Israelí'),
    ('Italia', '+39', 'Italiano'),
    ('Jamaica', '+1-876', 'Jamaicano'),
    ('Japón', '+81', 'Japonés'),
    ('Jordania', '+962', 'Jordano'),
    ('Kazajistán', '+7', 'Kazajo'),
    ('Kenia', '+254', 'Keniano'),
    ('Kirguistán', '+996', 'Kirguís'),
    ('Kiribati', '+686', 'Kiribatiano'),
    ('Kuwait', '+965', 'Kuwaití'),
    ('Laos', '+856', 'Laosiano'),
    ('Lesoto', '+266', 'Lesotense'),
    ('Letonia', '+371', 'Letón'),
    ('Líbano', '+961', 'Libanés'),
    ('Liberia', '+231', 'Liberiano'),
    ('Libia', '+218', 'Libio'),
    ('Liechtenstein', '+423', 'Liechtensteiniano'),
    ('Lituania', '+370', 'Lituano'),
    ('Luxemburgo', '+352', 'Luxemburgués'),
    ('Madagascar', '+261', 'Malgache'),
    ('Malasia', '+60', 'Malasio'),
    ('Malaui', '+265', 'Malauí'),
    ('Maldivas', '+960', 'Maldivo'),
    ('Malí', '+223', 'Maliense'),
    ('Malta', '+356', 'Maltés'),
    ('Marruecos', '+212', 'Marroquí'),
    ('Mauricio', '+230', 'Mauriciano'),
    ('Mauritania', '+222', 'Mauritano'),
    ('México', '+52', 'Mexicano'),
    ('Micronesia', '+691', 'Micronesio'),
    ('Moldavia', '+373', 'Moldavo'),
    ('Mónaco', '+377', 'Monegasco'),
    ('Mongolia', '+976', 'Mongol'),
    ('Montenegro', '+382', 'Montenegrino'),
    ('Mozambique', '+258', 'Mozambiqueño'),
    ('Namibia', '+264', 'Namibio'),
    ('Nauru', '+674', 'Nauruano'),
    ('Nepal', '+977', 'Nepalí'),
    ('Nicaragua', '+505', 'Nicaragüense'),
    ('Níger', '+227', 'Nigerino'),
    ('Nigeria', '+234', 'Nigeriano'),
    ('Noruega', '+47', 'Noruego'),
    ('Nueva Zelanda', '+64', 'Neozelandés'),
    ('Omán', '+968', 'Omaní'),
    ('Países Bajos', '+31', 'Neerlandés'),
    ('Pakistán', '+92', 'Pakistani'),
    ('Palaos', '+680', 'Palaosiano'),
    ('Palestina', '+970', 'Palestino'),
    ('Panamá', '+507', 'Panameño'),
    ('Papúa Nueva Guinea', '+675', 'Papú'),
    ('Paraguay', '+595', 'Paraguayo'),
    ('Perú', '+51', 'Peruano'),
    ('Polonia', '+48', 'Polaco'),
    ('Portugal', '+351', 'Portugués'),
    ('Reino Unido', '+44', 'Británico'),
    ('República Centroafricana', '+236', 'Centroafricano'),
    ('República Checa', '+420', 'Checo'),
    ('República de Macedonia', '+389', 'Macedonio'),
    ('República del Congo', '+242', 'Congolés'),
    ('República Democrática del Congo', '+243', 'Congolés'),
    ('República Dominicana', '+1-809, +1-829, +1-849', 'Dominicano'),
    ('República Popular China', '+86', 'Chino'),
    ('Ruanda', '+250', 'Ruandés'),
    ('Rumania', '+40', 'Rumano'),
    ('Rusia', '+7', 'Ruso'),
    ('Samoa', '+685', 'Samoano'),
    ('San Cristóbal y Nieves', '+1-869', 'San Cristobalense, Nivense'),
    ('San Marino', '+378', 'Sanmarinense'),
    ('San Vicente y las Granadinas', '+1-784', 'Sanvicentino'),
    ('Santa Lucía', '+1-758', 'Santalucense'),
    ('Santo Tomé y Príncipe', '+239', 'Santomense'),
    ('Senegal', '+221', 'Senegalés'),
    ('Serbia', '+381', 'Serbio'),
    ('Seychelles', '+248', 'Seychellense'),
    ('Sierra Leona', '+232', 'Sierraleonés'),
    ('Singapur', '+65', 'Singapurense'),
    ('Siria', '+963', 'Sirio'),
    ('Somalia', '+252', 'Somalí'),
    ('Sri Lanka', '+94', 'Ceilanés, Sri Lanka'),
    ('Sudáfrica', '+27', 'Sudafricano'),
    ('Sudán', '+249', 'Sudanés'),
    ('Sudán del Sur', '+211', 'Sursudanés'),
    ('Suecia', '+46', 'Sueco'),
    ('Suiza', '+41', 'Suizo'),
    ('Surinam', '+597', 'Surinamés'),
    ('Tailandia', '+66', 'Tailandés'),
    ('Taiwán', '+886', 'Taiwanés'),
    ('Tanzania', '+255', 'Tanzano'),
    ('Tayikistán', '+992', 'Tayiko'),
    ('Timor Oriental', '+670', 'Timorense'),
    ('Togo', '+228', 'Togolés'),
    ('Tonga', '+676', 'Tongano'),
    ('Trinidad y Tobago', '+1-868', 'Trinitense, Tobagense'),
    ('Túnez', '+216', 'Tunecino'),
    ('Turkmenistán', '+993', 'Turcomano'),
    ('Turquía', '+90', 'Turco'),
    ('Tuvalu', '+688', 'Tuvaluano'),
    ('Ucrania', '+380', 'Ucraniano'),
    ('Uganda', '+256', 'Ugandés'),
    ('Uruguay', '+598', 'Uruguayo'),
    ('Uzbekistán', '+998', 'Uzbeko'),
    ('Vanuatu', '+678', 'Vanuatuense'),
    ('Venezuela', '+58', 'Venezolano'),
    ('Vietnam', '+84', 'Vietnamita'),
    ('Yemen', '+967', 'Yemení'),
    ('Yibuti', '+253', 'Yibutiano'),
    ('Zambia', '+260', 'Zambiano'),
    ('Zimbabue', '+263', 'Zimbabuense');




CREATE TABLE huespedes (
    id_huesped INT PRIMARY KEY AUTO_INCREMENT,
    nombre VARCHAR(100) NOT NULL,
    apellido VARCHAR(100) NOT NULL,
    fecha_nacimiento DATE NOT NULL,
    telefono VARCHAR(20) NOT NULL UNIQUE,
    id_pais INT NOT NULL,
    id_reserva INT,
    FOREIGN KEY (id_pais) REFERENCES paises(id_pais),
    FOREIGN KEY (id_reserva) REFERENCES reservas(id_reserva) ON DELETE SET NULL ON UPDATE CASCADE
);

-- Creamos los nuevos triggers para calcular el valor automáticamente
DELIMITER //

-- Trigger para el evento INSERT
CREATE TRIGGER calcular_valor_reserva_insert BEFORE INSERT ON Reservas
FOR EACH ROW
BEGIN
  SET NEW.valor = 100 * DATEDIFF(NEW.fecha_salida, NEW.fecha_entrada);
END;

-- Trigger para el evento UPDATE
CREATE TRIGGER calcular_valor_reserva_update BEFORE UPDATE ON Reservas
FOR EACH ROW
BEGIN
  SET NEW.valor = 100 * DATEDIFF(NEW.fecha_salida, NEW.fecha_entrada);
END;
//
DELIMITER ;

Select * from Reservas;
Select * from Huespedes;
Select * from Paises;
